USE medical_booking;

ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500) NULL;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS poster_url VARCHAR(500) NULL;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS working_time VARCHAR(255) NULL;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE hospitals ADD COLUMN IF NOT EXISTS rating DECIMAL(2,1) DEFAULT 4.5;
